/**
 * Generated by tsnapi — public API snapshot of `git-stage-lines`
 */
// #region Types
export type FindBinaryOptions = {
  binaryPath?: string;
  cwd?: string;
  env?: Record<string, string | undefined>;
};
export type StageLinesCheckedResult = {
  status: 'checked';
  file: string;
  ranges: string[];
  mode: StageLinesMode;
  selected_changes: number;
  skipped_changes: number;
  patch_applied: false;
  would_apply: true;
};
export type StageLinesDryRunResult = {
  status: 'dry-run';
  file: string;
  ranges: string[];
  mode: StageLinesMode;
  selected_changes: number;
  skipped_changes: number;
  patch_applied: false;
  would_apply: true;
  patch: string;
};
export type StageLinesErrorResult = {
  status: 'error';
  reason: string;
  message: string;
  file?: string;
  ranges?: string[];
  exit_code?: number;
  stderr?: string;
};
export type StageLinesMode = 'new' | 'old' | 'both';
export type StageLinesNoopResult = {
  status: 'noop';
  file: string;
  ranges: string[];
  mode: StageLinesMode;
  selected_changes: 0;
  skipped_changes: number;
  patch_applied: false;
  would_apply?: boolean;
  reason: 'no_matching_changes' | 'empty_patch' | 'no_unstaged_changes';
};
export type StageLinesOptions = {
  file: string;
  ranges: string | StageLinesRange[];
  mode?: StageLinesMode;
  cwd?: string;
  binaryPath?: string;
  dryRun?: boolean;
  check?: boolean;
  allowEmpty?: boolean;
  verbose?: boolean;
  env?: Record<string, string | undefined>;
  signal?: AbortSignal;
};
export type StageLinesRange = number | [number, number];
export type StageLinesResult = StageLinesSuccessResult | StageLinesCheckedResult | StageLinesDryRunResult | StageLinesNoopResult | StageLinesErrorResult;
export type StageLinesSuccessResult = {
  status: 'staged';
  file: string;
  ranges: string[];
  mode: StageLinesMode;
  selected_changes: number;
  skipped_changes: number;
  patch_applied: true;
  would_apply?: boolean;
};
// #endregion

// #region Classes
export declare class GitStageLinesError extends Error {
  reason: string;
  exitCode?: number;
  result?: StageLinesErrorResult;
  stderr?: string;
  constructor(_: string, _: {
    reason: string;
    exitCode?: number;
    result?: StageLinesErrorResult;
    stderr?: string;
    cause?: unknown;
  });
}
// #endregion

// #region Functions
export declare function checkStageLines(_: StageLinesOptions): Promise<StageLinesResult>;
export declare function dryRunStageLines(_: StageLinesOptions): Promise<StageLinesResult>;
export declare function findBinary(_?: FindBinaryOptions): string;
export declare function stageLines(_: StageLinesOptions): Promise<StageLinesResult>;
export declare function stageLinesSync(_: StageLinesOptions): StageLinesResult;
// #endregion